#!/bin/bash
# MIT License
# Copyright (c) 2022 Gauthier FRANCOIS

export RACK_ENV=production

# Mandatory for Ruby environment manager rbenv
export PATH="/var/www/.rbenv/shims/:${PATH}"

# Change home directory for Sinatra application
export HOME=/var/www/TimerStartX

bundle exec rackup -s thin -o 0.0.0.0
